Gem update & Ruby version 3.2.0 support
paperkite/paperkite-rubocop pull request #7
Opened 2023-02-13 20:25 UTC by deep12650

This PR is for Gem spec update and ruby version 3.2.0 support.

2023-02-13 20:50 UTC, invke requested changes
The version should be `1.1.1-beta.1` shouldn't it? You've skipped some things. I think semantically it shouldn't have gone from `1.0.0-beta.6` to `1.1.0-beta.1`, that's not the order of semantic versioning.

Instead, you could release this as `v1.0.0` if we want to drop the beta tag and delete the `v1.1.0-beta.1` version.

2023-02-13 21:23 UTC, kyokokj commented
Ok, I just understood the order of semantic versioning. thanks!
and question.
So the version of Gem is checked strictly and if the order is not correct, it doesn't work????

2023-02-13 21:28 UTC, invke approved these changes

2023-02-14 01:19 UTC, kyokokj approved these changes

2023-02-14 03:30 UTC, merged